---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: task03
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task03
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: task03
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task03
  labels:
    app: task03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task03
  template:
    metadata:
      labels:
        app: task03
    spec:
      initContainers:
        - name: busybox-init
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Initializing shared volume (PVC with custom SC)" | tee -a /shared/output.txt
          volumeMounts:
            - name: shared-data
              mountPath: /shared
      containers:
        - name: busybox
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                echo "$(date '+%Y-%m-%d %H:%M:%S') - hello from busybox" | tee -a /shared/output.txt
                sleep 5
              done
          volumeMounts:
            - name: shared-data
              mountPath: /shared
        - name: multitool
          image: wbitt/network-multitool
          command: ["tail"]
          args:
            - -f
            - /shared/output.txt
          volumeMounts:
            - name: shared-data
              mountPath: /shared
              readOnly: true
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: task03
